env = Environment(CCFLAGS='-O9 -std=c++0x',
                    CPPPATH=['include'])

src_files = ['main.cc', 'netsight.cc', 'path_table.cc']

lib_deps = []
lib_paths = []

lib_deps.append('netsightlib')
lib_paths.append('lib')

lib_deps.append('filter')
lib_paths.append('filter')

lib_deps.append('sort')
lib_paths.append('topo_sort')

lib_deps.append('compress')
lib_paths.append('compress')

lib_deps.append('bpfjit')
lib_paths.append('filter/bpf-linux')

lib_deps += ['pcap', 'pthread', 'z']

env.Program(target='netsight', source=src_files,
            LIBS=lib_deps, LIBPATH=lib_paths,
            RPATH=['filter/bpf-linux'])

SConscript(['lib/SConscript', 'filter/SConscript', 'topo_sort/SConscript',
            'compress/SConscript'])
