Import('debug')
env = Environment(CCFLAGS=['-O9', '-std=c++0x'],
                    CPPPATH=['.', '#netsight/src/include', '#netsight/src'])

if debug:
    env.Append(CCFLAGS='-g')
    env.Append(CPPDEFINES='DEBUG')

src_files = ['main.cc', 'test_compress.cc', 'test_filter.cc', 'test_sort.cc',
'test_util.cc']

lib_deps = []
lib_paths = []

lib_deps.append('netsightlib')
lib_paths.append('#netsight/src/lib')

lib_deps.append('filter')
lib_paths.append('#netsight/src/filter')

lib_deps.append('sort')
lib_paths.append('#netsight/src/topo_sort')

lib_deps.append('compress')
lib_paths.append('#netsight/src/compress')

lib_deps.append('bpfjit')
lib_paths.append('#netsight/src/filter/bpf-linux')

lib_deps += ['crafter', 'pcap', 'pthread', 'z']

env.Program(target='test_netsight', source=src_files,
            LIBS=lib_deps, LIBPATH=lib_paths,
            RPATH=[Dir('#').path + '/netsight/src/filter/bpf-linux'])
