Import('env')

src_files = ['topo_sort.cc']
lib_deps = ['netsightlib']
lib_paths = ['#netsight/src/lib']
env.StaticLibrary(target='sort', source=src_files, 
                    LIBS=lib_deps, LIBPATH=lib_paths)

