Import('env');

src_files = ['main.cc', 'ndb.cc']

lib_deps = []
lib_paths = []

lib_deps.append('netsightlib')
lib_paths.append('#netsight/src/lib')

lib_deps.append('netsightapi')
lib_paths.append('#netsight/src/api')

lib_deps += ['pcap', 'pthread', 'z', 'zmq',
         'mongoclient', 'boost_thread-mt', 'boost_filesystem', 
         'boost_program_options', 'boost_system']

env.Program(target='ndb', source=src_files,
            LIBS=lib_deps, LIBPATH=lib_paths)
